apiVersion: 1
groups:
  - name: webapp-alerts
    folder: ""
    interval: 1m
    rules:
      - uid: high-error-rate
        title: High Error Rate
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (sum(rate(http_errors_total[5m])) / clamp_min(sum(rate(http_requests_total[5m])), 1e-9)) * 100
              interval: ""
              intervalFactor: 2
              legendFormat: "Error %"
              refId: A
              format: time_series
              datasource: Prometheus
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (sum(rate(http_errors_total[5m])) / clamp_min(sum(rate(http_requests_total[5m])), 1e-9)) * 100 > 5
              interval: ""
              intervalFactor: 2
              legendFormat: "Error % > 5"
              refId: B
              format: time_series
              datasource: Prometheus
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations:
          summary: "High error rate detected (>5%)"
          description: "Error rate is above 5% over the last 5 minutes."
        labels:
          severity: warning
